#!/bin/bash 
#This script tries to run BADUDPGW automatically 
#Esse script tenta rodar o BADUDPGW automaticamente  
### BEGIN INIT INFO
# Provides:          badudp
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: inicia badvpn-udpgw
### END INIT INFO

case "$1" in
	"start") screen -Dms badudp "/bin/badudp"
		;;
	"stop") killall badvpn-udpgw
            screen -wipe
		;;
	"restart") killall badvpn-udpgw
			screen -Dms badudp "/bin/badudp"
			screen -wipe
		;;
	*) echo "Iniciando UDP..." 
		screen -Dms badudp "/bin/badudp"
		screen -wipe
		;;
esac
