#!/bin/bash
### BEGIN INIT INFO
# Provides:          Polipov2
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Polipov2
# Description:       Polipov2 service
### END INIT INFO

case "$1" in

  start)
       screen -dmS Polipo2	   "/usr/sbin/polipo2"
        ;;
  stop)
        PID=`ps -ef | grep polipo | grep -v grep | awk '{print $2}'`
        kill -9 $PID
        screen -wipe
        ;;

  restart|force-reload)
        PID=`ps -ef | grep polipo | grep -v grep | awk '{print $2}'`
        kill -9 $PID 
        sleep 3
        screen -dmS Polipo2 "/usr/sbin/polipo2"
        screen -wipe
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart}" >&2
        exit 1
        ;;
esac
exit 0
