#!/bin/bash
### BEGIN INIT INFO
# Provides:          greenviewcore
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts greenview core
# Description:       Enables greenview to work on background
### END INIT INFO

case "$1" in

  start)
        echo "Starting GreenView"
       screen -dmS greenview "/usr/lib/greenview/corebase"
        ;;
  stop)
        echo "Stopping GreenView"
        PID=`ps -ef | grep corebase | grep -v grep | awk '{print $2}'`
        kill -9 $PID
        screen -wipe
        ;;

  restart|force-reload)
        echo "Restarting GreenView"
        PID=`ps -ef | grep corebase | grep -v grep | awk '{print $2}'`
        kill -9 $PID 
        sleep 3
        screen -dmS greenview "/usr/lib/greenview/corebase"
        screen -wipe
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart}" >&2
        exit 1
        ;;
esac
exit 0
