#!/bin/bash
### BEGIN INIT INFO
# Provides:          SSLTun
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: SSLTun
# Description:       SSLTun service
### END INIT INFO

case "$1" in

  start)
       screen -dmS SSLTun	   "stunnel4"
        ;;
  stop)
        PID=`ps -ef | grep stunnel4 | grep -v grep | awk '{print $2}'`
        kill -9 $PID
        screen -wipe
        ;;

  restart|force-reload)
        PID=`ps -ef | grep stunnel4 | grep -v grep | awk '{print $2}'`
        kill -9 $PID 
        sleep 3
        screen -dmS SSLTun "stunnel4"
        screen -wipe
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart}" >&2
        exit 1
        ;;
esac
exit 0
